# Generated by Django 6.0 on 2025-12-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_lat_service_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
    ]
