# Generated by Django 6.0 on 2026-01-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='consumerprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='landmark',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
