# Generated by Django 6.0 on 2026-01-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_consumerprofile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='providers/covers/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='owner_image',
            field=models.ImageField(blank=True, null=True, upload_to='providers/owners/'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
