# Generated by Django 6.0 on 2026-01-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_providerprofile_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='consumers/'),
        ),
    ]
